---
apiVersion: v1
kind: Pod
metadata:
  name: grafanapod
  labels:
    components: grafana

spec:
  containers:
    - name: grafana
      image: grafana/grafana
      ports:
        - containerPort: 3000

            
